# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: thoughts.md
email: maxkerp@gmail.com
description: >
  My place to ramble about code, ideas, and life.
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maxkerp.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Max Kerp'
bio: >
  I'm almost done studying computer science and I currently work part time
  as a rails developer at <a target="_blank" href="http://taktsoft.com">taktsoft</a>.
  I love to learn things, that make life easier.
  Currently i'm playing around with web components and related
  projects like angular, ember, react and vue.
author_image: "/assets/images/author.jpg"
twitter_username: maxkerp
github_username:  maxkerp

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
